var a = "peach"
var brf = "oat meal"
var dss = "bar of lard"
var ds = "crazy animals"
var vv = "archer"
var ccccc = "super man"
var u = "barf"
var n = "please eat me"
var nd = "are"
var m = "run for your life"
console.log(a[0] + brf[0] + dss[7] + ds[2] + vv[1] + ccccc[5] + u[0] + n[2] + nd[0] + m[0]);
