var a = "javascript is awesome!";
var b = 3 == 3;
var c = "polar bears are awesome!!!";
var d = 4 == 4;
var t = "Are seals awesome?";
var r = "not at all.";
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(t);
console.log(r);